from kconfiglib import Kconfig

kconf = Kconfig("Kconfig")
kconf.load_config(".config")

with open("config.h", "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by Kconfig */\n")
    f.write("#pragma once\n\n")

    for sym in sorted(kconf.unique_defined_syms, key=lambda s: s.name):
        if sym.str_value == "y":
            f.write(f"#define CONFIG_{sym.name} 1\n")
        else:
            f.write(f"/* CONFIG_{sym.name} is not set */\n")
