# genconfig.py
import re

CONFIG_FILE = ".config"
OUTPUT_FILE = "config.h"

def parse_config_line(line):
    """
    返回 (key, value) 或 None
    """
    line = line.strip()

    if not line:
        return None

    # unset
    if line.startswith("#"):
        return None

    if "=" not in line:
        return None

    key, val = line.split("=", 1)
    return key, val


def emit_define(out, key, val):
    # bool
    if val == "y":
        out.write(f"#define {key} 1\n")
    # string
    elif val.startswith('"') and val.endswith('"'):
        out.write(f"#define {key} {val}\n")
    # int / hex
    else:
        out.write(f"#define {key} {val}\n")


def main():
    with open(OUTPUT_FILE, "w", encoding="utf-8") as out:
        out.write("/* Auto-generated by Kconfig */\n")
        out.write("#pragma once\n\n")

        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            for line in f:
                parsed = parse_config_line(line)
                if not parsed:
                    continue

                key, val = parsed
                emit_define(out, key, val)


if __name__ == "__main__":
    main()
